//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contratos
    {
        public int Contratos_Id { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public int TipoContrato_Id { get; set; }
        public string ObjetoContractual { get; set; }
        public Nullable<System.DateTime> Plazo { get; set; }
        public Nullable<System.DateTime> FechaTerminacion { get; set; }
        public Nullable<int> PersonaAbogado_Id { get; set; }
        public Nullable<int> PersonaSuperviosr_Id { get; set; }
        public Nullable<int> Crp { get; set; }
        public Nullable<int> Cdp { get; set; }
        public Nullable<System.DateTime> FechaActaInicio { get; set; }
        public Nullable<int> TipoEstadoContrato_Id { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> ValorContrato { get; set; }
        public Nullable<decimal> ValorAdministrar { get; set; }
        public Nullable<decimal> Honorarios { get; set; }
        public string PorcentajeFacturado { get; set; }
        public string PorcentajeFacturadoHonorarios { get; set; }
        public Nullable<int> PersonaSupervisorTecnico_Id { get; set; }
        public Nullable<int> ContratoMarco_Id { get; set; }
    
        public virtual ContratosMarco ContratosMarco { get; set; }
        public virtual TiposContratos TiposContratos { get; set; }
        public virtual Personas Personas { get; set; }
        public virtual Personas Personas1 { get; set; }
        public virtual TiposEstadoContrato TiposEstadoContrato { get; set; }
    }
}
