//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GCP_BDEntities : DbContext
    {
        public GCP_BDEntities()
            : base("name=GCP_BDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contratos> Contratos { get; set; }
        public virtual DbSet<ContratosMarco> ContratosMarco { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TiposContratos> TiposContratos { get; set; }
        public virtual DbSet<TiposPersona> TiposPersona { get; set; }
        public virtual DbSet<TiposEstadoContrato> TiposEstadoContrato { get; set; }
        public virtual DbSet<TiposNaturaleza> TiposNaturaleza { get; set; }
    }
}
